kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hive-pvc
  labels:
    name: hive-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hive
  labels:
    presto: hive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        presto: hive
    spec:
      containers:
      - image: ehallmark1122/docker-hive
        command: [/etc/hive-bootstrap.sh]
        name: presto-hive
        ports:
        - containerPort: 9083
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/apps/hive/warehouse"
            name: data-storage
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: hive-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hive
spec:
  selector:
    presto: hive
  type: NodePort
  ports:
    - port: 9083
