kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: presto-worker-pvc
  labels:
    name: presto-worker-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    presto: worker
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        presto: worker
    spec:
      containers:
      - env:
        - name: HTTP_SERVER_PORT
          value: "8080"
        - name: PRESTO_JVM_HEAP_SIZE
          value: "8"
        - name: PRESTO_MAX_MEMORY
          value: "10"
        - name: PRESTO_MAX_MEMORY_PER_NODE
          value: "1"
        - name : COORDINATOR
          value: "presto"
        image: ehallmark1122/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 3
          periodSeconds: 300
          timeoutSeconds: 10
        name: worker
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/var/lib/presto/data"
            name: data-storage
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: presto-worker-pvc
      restartPolicy: Always
